services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-collection-service
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: ["sh", "-c", "pnpm prisma generate && pnpm start:dev"]
    networks:
      - default

volumes:
  node_modules:

networks:
  default:
    external: true
    name: carddock-network
