export enum CardCondition {
  MINT = 'MINT',
  NEAR_MINT = 'NEAR_MINT',
  LIGHTLY_PLAYED = 'LIGHTLY_PLAYED',
  PLAYED = 'PLAYED',
  DAMAGED = 'DAMAGED',
}

export enum CardRarity {
  COMMON = 'COMMON',
  RARE = 'RARE',
  SUPER_RARE = 'SUPER_RARE',
  ULTRA_RARE = 'ULTRA_RARE',
  SECRET_RARE = 'SECRET_RARE',
  ULTIMATE_RARE = 'ULTIMATE_RARE',
  GHOST_RARE = 'GHOST_RARE',
  PRISMATIC_SECRET_RARE = 'PRISMATIC_SECRET_RARE',
  STARLIGHT_RARE = 'STARLIGHT_RARE',
  COLLECTORS_RARE = 'COLLECTORS_RARE',
}

export enum CardEdition {
  FIRST_EDITION = 'FIRST_EDITION',
  UNLIMITED = 'UNLIMITED',
}
